name: Deploy Java App (No Tomcat)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MY_PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.MY_IP }} >> ~/.ssh/known_hosts

    - name: Copy JAR file to EC2
      run: |
        scp -i ~/.ssh/id_rsa ./your-app.jar ${{ secrets.MY_IP }}@${{ secrets.MY_IP }}:/home/${{ secrets.MY_IP }}/your-app.jar

    - name: SSH into EC2 and install Java 17
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.MY_IP }}@${{ secrets.MY_IP }} << 'EOF'
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk

          # Optional: Stop any existing Java process (based on your setup)
          pkill -f 'java -jar' || true

          # Run the app in the background
          nohup java -jar /home/${{ secrets.MY_IP }}/your-app.jar > app.log 2>&1 &
        EOF
