name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MY_PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.MY_IP }} >> ~/.ssh/known_hosts

    - name: Copy app to EC2
      run: |
        rsync -avz --exclude '.git' ./ ${{ secrets.MY_IP }}@${{ secrets.MY_IP }}:/home/${{ secrets.MY_IP }}/app/

    - name: Run app on EC2
      run: |
        ssh ${{ secrets.MY_IP }}@${{ secrets.MY_IP }} << 'EOF'
          cd ~/app
          nohup python3 app.py > server.log 2>&1 &
        EOF
