name: Start App on Amazon Linux EC2

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner (it's ok!)

    steps:
      - name: Set up SSH for EC2 connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_PEM_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Run app on Amazon Linux EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.MY_IP }} << 'EOF'
            # Move to the directory where your app is located
            cd ~/app

            # Activate virtual environment (assumes it's already there)
            source venv/bin/activate

            # Kill old process if any
            pkill -f app.py || true

            # Start the app (e.g., Python web server)
            nohup python3 app.py > app.log 2>&1 &
          EOF
