name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MY_PEM_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.MY_IP }} >> ~/.ssh/known_hosts

    - name: Copy project files to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.ubuntu }}@${{ secrets.MY_IP }} "rm -rf ~/app && mkdir -p ~/app"
        scp -i ~/.ssh/id_rsa -r . ${{ secrets.ubuntu }}@${{ secrets.MY_IP }}:~/app

    - name: Run the app on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.ubuntu }}@${{ secrets.MY_IP }} << 'EOF'
          cd ~/app
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-venv
          
          # Optional: Set up Python venv
          python3 -m venv venv
          source venv/bin/activate

          # Install requirements if requirements.txt exists
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

          # Kill old app process if running (Python example)
          pkill -f "python3 app.py" || true

          # Run the app in background
          nohup python3 app.py > app.log 2>&1 &
        EOF
