name: py

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: build  # Deploy only if builds pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up SSH and Connect to Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MY_PEM }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.MY_IP }} >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.MY_IP }} "echo '✅ Successfully connected to the server'"

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.MY_IP }} << 'EOF'
          cd /home/ubuntu/app
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart myapp
          EOF

      - name: Restart Application
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.MY_IP }} "sudo systemctl restart myapp.service"



